"use strict";
let AfridiNumber = 10;
let Score = "50";
console.log(AfridiNumber == 10);
console.log(AfridiNumber === 10);
console.log(AfridiNumber == '10');
console.log(AfridiNumber == 20 - 10);
console.log(AfridiNumber === 5 * 2);
console.log(AfridiNumber === '10');
console.log(AfridiNumber == 20 + 1);
console.log(Score === 60 - 10);
console.log(Score == AfridiNumber);
