"use strict";
let today = "sat";
let todayDate = 1;
let color = "White";
const fruits = ["Banana", "Orange", "Apple", "Mango"];
console.log(todayDate === 1);
console.log(todayDate === '1');
console.log(today === today.toLowerCase());
console.log(today > 2);
console.log(today < 2);
console.log(todayDate == '1');
console.log(today < 2 || todayDate == '1');
console.log(today < 2 || todayDate === '1');
console.log(today == "sat" && todayDate == '1');
console.log(today == "sat" && todayDate === '1');
console.log(fruits.includes("Mango"));
console.log(fruits.includes("grapes"));
